version: '3'
services:
  survey-management-system:
    image: oracle-app
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
